# Generated by Django 4.2.9 on 2025-11-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('max_attendees', models.PositiveIntegerField()),
                ('price', models.IntegerField(default=0)),
                ('event_cover', models.ImageField(blank=True, null=True, upload_to='media/events/')),
            ],
        ),
    ]
