# Generated by Django 4.2.9 on 2025-12-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_events_created_at_events_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
