# Generated by Django 4.2.9 on 2025-12-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_events_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='attendees',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
