# Generated by Django 4.2.9 on 2025-12-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_events_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_cover',
            field=models.ImageField(blank=True, null=True, upload_to='`media/events/`'),
        ),
    ]
