# Generated by Django 4.2.9 on 2025-12-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0002_alter_invitetoken_token_alter_rsvp_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitetoken',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
