# Generated by Django 4.2.9 on 2025-12-08 07:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0003_invitetoken_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
