# Generated by Django 4.2.9 on 2025-12-09 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0005_events_attendees'),
        ('rsvp', '0005_alter_rsvp_unique_together_rsvp_invite_token_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rsvp',
            unique_together={('event', 'user')},
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
