# Generated by Django 4.2.9 on 2025-11-20 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=250, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='users/profile/')),
                ('is_admin', models.BooleanField(default=False)),
                ('date_join', models.DateTimeField(default=django.utils.timezone.now)),
                ('attend_number_of_event', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
