# Generated by Django 4.2.9 on 2025-12-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_created_at_users_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='reset_otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
