# Generated by Django 4.2.9 on 2025-12-21 19:42

from django.db import migrations
import os

def create_superuser(apps, schema_editor):
    User = apps.get_model("users", "Users")

    username = os.environ.get("DJANGO_SUPERUSER_USERNAME")
    email = os.environ.get("DJANGO_SUPERUSER_EMAIL")
    password = os.environ.get("DJANGO_SUPERUSER_PASSWORD")
   
    if not username or not password:
        return

    if not User.objects.filter(username=username).exists():
        User.objects.create_superuser(
            username=username,
            email=email,
            password=password
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_reset_otp'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]